### PR TITLE
Fix repos bug

### LINKED ISSUE #458: Fix repos dir creation bug
If you call `subnet publish`, it fails with a directory doesn't exist error.

### PR DESCRIPTION
**Pull request by dasconnor**
Creates the `repos` directory in the root command if it doesn't exist.

Closes #458

### CODE REVIEW

File: cmd/root.go [hunk 1]
```diff
@@ -148,6 +148,13 @@ func setupEnv() (string, error) {
 		os.Exit(1)
 	}
 
+	// Create repos dir if it doesn't exist
+	repoDir := filepath.Join(baseDir, constants.ReposDir)
```
Comment (holisticode) [inline cmd/root.go:152]: Shouldn't this also be subnet dependent now?

Comment (holisticode) [reply cmd/root.go:152]: OK let's pass this now as a fix and address later

**Review by holisticode — APPROVED** [review]
