### PR TITLE
Fix addValidator Defaults

### LINKED ISSUE #132: Add default stake weight
We should provide a default suggestion for stake weight when whitelisting a validator.

### LINKED ISSUE #142: Fix default start time and duration

### LINKED ISSUE #143: VMs should go to /tmp

### PR DESCRIPTION
**Pull request by dasconnor**
I reworked how `addValidator` captures fields to make it more like our `subnet create` flow. We specify default values even if not provided but also allow users to customize.

The default start time is five minutes from now. The default weight is 20 and the default duration is the validator's end time on the primary network.

Closes #142 Closes #143 Closes #132

### CODE REVIEW

File: pkg/constants/constants.go [hunk 1]
```diff
@@ -46,10 +46,17 @@ const (
...
-	TimeParseLayout      = "2006-01-02 15:04:05"
-	MinStakeDuration     = 24 * 14 * time.Hour
-	MaxStakeDuration     = 24 * 365 * time.Hour
-	StakingStartLeadTime = 25 * time.Second
+	TimeParseLayout  = "2006-01-02 15:04:05"
+	MinStakeDuration = 24 * 14 * time.Hour
+	MaxStakeDuration = 24 * 365 * time.Hour
+	MaxStakeWeight   = 100
+	MinStakeWeight   = 1
+	DefaultWeight    = 20
```
Comment (felipemadero) [inline pkg/constants/constants.go:54]: DefaultStakeWeight?

File: pkg/constants/constants.go [hunk 2]
```diff
@@ -46,10 +46,17 @@ const (
...
+
+	// The absolute minimum is 25 seconds, but set to 5 minutes to allow for
```
Comment (felipemadero) [inline pkg/constants/constants.go:56]: set to 1 minute

File: pkg/prompts/prompts.go [hunk 3]
```diff
@@ -37,7 +37,7 @@ type Prompter interface {
 	CaptureDuration(promptStr string) (time.Duration, error)
 	CaptureDate(promptStr string) (time.Time, error)
 	CaptureNodeID(promptStr string) (ids.NodeID, error)
-	CaptureWeight(promptStr string) (uint64, error)
+	CaptureWeight(promptStr string) (int64, error)
```
Comment (felipemadero) [inline pkg/prompts/prompts.go:40]: why int ? negative values?

File: cmd/subnetcmd/addValidator.go [hunk 4]
```diff
@@ -48,16 +50,16 @@ This command currently only works on subnets deployed to the Fuji testnet.`,
 	}
 	cmd.Flags().StringVarP(&keyName, "key", "k", "", "select the key to use")
 	cmd.Flags().StringVar(&nodeIDStr, "nodeID", "", "set the NodeID of the validator to add")
-	cmd.Flags().StringVar(&weightStr, "weight", "", "set the staking weight of the validator to add")
-	cmd.Flags().StringVar(&startTimeStr, "start-time", startTimeDefault.Format(constants.TimeParseLayout), "start time when this validator starts validating, in 'YYYY-MM-DD HH:MM:SS' format")
-	cmd.Flags().DurationVar(&duration, "staking-period", constants.MaxStakeDuration, "how long this validator will be staking")
+	cmd.Flags().Int64Var(&weight, "weight", 0, "set the staking weight of the validator to add")
```
Comment (felipemadero) [inline cmd/subnetcmd/addValidator.go:53]: I think you have Uint64Var available

File: cmd/subnetcmd/addValidator.go [hunk 5]
```diff
@@ -165,8 +151,96 @@ func promptDuration(start time.Time) (time.Duration, error) {
...
+}
+
+func getTimeParameters(network models.Network, nodeID ids.NodeID) (time.Time, time.Duration, error) {
+	var (
+		start time.Time
+		err   error
+	)
+
+	const (
+		defaultStartOption    = "Start in five minutes"
```
Comment (felipemadero) [inline cmd/subnetcmd/addValidator.go:184]: 1 minute

File: cmd/subnetcmd/addValidator.go [hunk 6]
```diff
@@ -165,8 +151,96 @@ func promptDuration(start time.Time) (time.Duration, error) {
...
+
+		startTimeOptions := []string{defaultStartOption, custom}
+		startTimeOption, err := app.Prompt.CaptureList("Start time", startTimeOptions)
+		if err != nil {
+			return time.Time{}, 0, err
+		}
+
+		switch startTimeOption {
+		case defaultStartOption:
+			start = startTimeDefault
```
Comment (felipemadero) [inline cmd/subnetcmd/addValidator.go:201]: I think you are not setting this to now() + 1 minute stuff

Comment (felipemadero) [reply cmd/subnetcmd/addValidator.go:201]: I mean, this start shall be set just before creating the tx, to guarrante the minute

File: pkg/constants/constants.go (hunk 1 above)
Comment (dasconnor) [reply pkg/constants/constants.go]: fixed

File: pkg/prompts/prompts.go (hunk 3 above)
Comment (dasconnor) [reply pkg/prompts/prompts.go]: I didn't realize I could use uint in the flag :man_facepalming:

File: cmd/subnetcmd/addValidator.go (hunk 4 above)
Comment (dasconnor) [reply cmd/subnetcmd/addValidator.go]: I got tripped up, I thought it would be `UInt` not `Uint`. Fixed now.

File: cmd/subnetcmd/addValidator.go (hunk 5 above)
Comment (dasconnor) [reply cmd/subnetcmd/addValidator.go]: fixed

File: cmd/subnetcmd/addValidator.go (hunk 6 above)
Comment (dasconnor) [reply cmd/subnetcmd/addValidator.go]: great suggestion

**Review by felipemadero — APPROVED** [review]
