### PR TITLE
Fix Upgrade Compatibility

### LINKED ISSUE #377: Don't break Avalanche-CLI on avalanchego update
# Problem 

When a new version of Avalanchego releases, it may break compatibility with all previous versions of subnet-evm and spaces-vm. It may be hours or days before the appropriate version is released. In that in between window, avalanche-cli is broken by default and users must pass the `--avalanchego-version` flag. We need a scheme to prevent this from happening.

# Proposed Solution

Create a new API endpoint under `info`. It will list the avalanchego versions compatible with a given `rpcChainVMProtocolVersion`.

```
GET info.getVersionCompatibility

"params": {
  "rpcChainVmProtocolVersion": 17
}

Returns 
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "versions": ["v1.9.0", "v1.9.1"]
  }
}
```

## CLI Experience

1. At deploy time, CLI will check the `rpcChainVMProtocolVersion` of the desired VM.
2. The CLI will perform a lookup at api.avax.network to determine avago compatibility for the desired `rpcChainVMProtocolVersion`.
3. The CLI will launch with the latest avago from the compatibility list.

## Avago Release Experience

- When performing a release, the avago team will be responsible for adding the new release's compatibility into some config file prior to release

### PR DESCRIPTION
**Pull request by dasconnor**
This PR addresses the CLI compatibility breaks whenever Avalanchego updates. It now queries compatibility files hosted in the avalanchego and VM repos. It assumes that you are deploying a fixed VM version. First, we look up what RPC protocol version that VM uses, then we find the latest version of avalanchego compatible with that RPC version. That version of Avalanchego is the one we use for our deployment.

Closes #377

## Sumary of Changes
- Bump linter version
- Add RPCVersion to sidecar and track on subnet creation
- Select a valid version of avalanchego for the specified VM RPCVersion at deploy time
  - If you're running a custom VM, we don't track the RPCVersion and just give you latest
- Moved some of our http code to a new `Downloader` interface as part of the `application` package. I did this to facilitate testing by making it easier to mock network requests
- Created the `network` package to gather info about the currently running local network. Made it an interface to make it mockable.
- Fixed the spacing for the linter.
- Added code to fetch the current rpc version for a given VM version.
- E2E tests now use latest avago version by default
- Fixed package management tests to use a newer version
- Added a new compatibility E2E suite

### CODE REVIEW

File: pkg/application/downloader.go [hunk 1]
```diff
@@ -0,0 +1,78 @@
...
+		return "", fmt.Errorf("failed to get latest binary version from %s: %w", releaseURL, err)
+	}
+
+	var jsonStr map[string]interface{}
+	if err := json.Unmarshal(jsonBytes, &jsonStr); err != nil {
+		return "", fmt.Errorf("failed to unmarshal binary json version string: %w", err)
+	}
+
+	version := jsonStr["tag_name"].(string)
+	if version == "" || version[0] != 'v' {
```
Comment (holisticode) [inline pkg/application/downloader.go:73]: validate with semver?

File: pkg/application/downloader.go [hunk 2]
```diff
@@ -0,0 +1,78 @@
...
+	if err != nil {
+		return "", fmt.Errorf("failed to get latest binary version from %s: %w", releaseURL, err)
+	}
+
+	var jsonStr map[string]interface{}
+	if err := json.Unmarshal(jsonBytes, &jsonStr); err != nil {
+		return "", fmt.Errorf("failed to unmarshal binary json version string: %w", err)
+	}
+
+	version := jsonStr["tag_name"].(string)
```
Comment (holisticode) [inline pkg/application/downloader.go:72]: This could probably also go into a constant

File: pkg/application/downloader.go [hunk 3]
```diff
@@ -0,0 +1,78 @@
...
+	defer resp.Body.Close()
+	if resp.StatusCode != http.StatusOK {
+		return nil, fmt.Errorf("unexpected http status code: %d", resp.StatusCode)
+	}
+
+	return io.ReadAll(resp.Body)
+}
+
+// GetLatestReleaseVersion returns the latest available version from github
+func (downloader) GetLatestReleaseVersion(releaseURL string) (string, error) {
```
Comment (holisticode) [inline pkg/application/downloader.go:41]: A suggestion just for you to consider and decide: I think we are already using different downloaders, maybe we could have this be just a real downloader, without any "business" logic, downloading from the supplied URL, and then do version checks and stuff in a wrapper?

Comment (holisticode) [reply pkg/application/downloader.go:41]: Oh I see, this is basically just moved around. So we don't have maybe that many Downloaders after all.

File: pkg/network/network.go [hunk 4]
```diff
@@ -0,0 +1,43 @@
...
+	GetCurrentNetworkVersion() (string, int, error)
+}
+
+type networkStatusChecker struct{}
+
+func NewStatusChecker() StatusChecker {
+	return networkStatusChecker{}
+}
+
+func (networkStatusChecker) GetCurrentNetworkVersion() (string, int, error) {
```
Comment (holisticode) [inline pkg/network/network.go:26]: If the `string` returned is a semver version, maybe we could use that as the data type?

File: cmd/subnetcmd/deploy.go [hunk 5]
```diff
@@ -678,3 +692,45 @@ func PrintDeployResults(chain string, subnetID ids.ID, blockchainID ids.ID, isFu
 	table.Render()
 	return nil
 }
+
+// Has side effects and will set the version of avalanchego in the package-level avagoVersion variable.
```
Comment (felipemadero) [inline cmd/subnetcmd/deploy.go:696]: can we avoid the side effects? not so easy to follow flow

File: cmd/subnetcmd/deploy.go [hunk 6]
```diff
@@ -678,3 +692,45 @@ func PrintDeployResults(chain string, subnetID ids.ID, blockchainID ids.ID, isFu
...
+
+	// RPC Version was made available in the info API in avalanchego version v1.9.2. For prior versions,
+	// we will need to skip this check.
+	skipRPCCheck := false
+	if semver.Compare(runningAvagoVersion, "v1.9.2") == -1 {
+		skipRPCCheck = true
+	}
+
+	if networkRunning {
+		if avagoVersion == "latest" {
```
Comment (felipemadero) [inline cmd/subnetcmd/deploy.go:715]: probably will me more clear by using a more descriptive name, not just avagoVersion

File: pkg/vm/compatibility.go [hunk 7]
```diff
@@ -0,0 +1,95 @@
...
+		return 0, errors.New("unknown VM type")
+	}
+
+	compatibilityBytes, err := app.Downloader.Download(url)
+	if err != nil {
+		return 0, err
+	}
+
+	var parsedCompat models.VMCompatibility
+	err = json.Unmarshal(compatibilityBytes, &parsedCompat)
```
Comment (holisticode) [inline pkg/vm/compatibility.go:39]: if err ....

File: pkg/vm/compatibility.go [hunk 8]
```diff
@@ -0,0 +1,95 @@
...
+}
+
+func GetLatestAvalancheGoByProtocolVersion(app *application.Avalanche, rpcVersion int) (string, error) {
+	compatibilityBytes, err := app.Downloader.Download(constants.AvalancheGoCompatibilityURL)
+	if err != nil {
+		return "", err
+	}
+
+	var parsedCompat models.AvagoCompatiblity
+	err = json.Unmarshal(compatibilityBytes, &parsedCompat)
```
Comment (holisticode) [inline pkg/vm/compatibility.go:59]: if err....

File: pkg/constants/constants.go [hunk 9]
```diff
@@ -100,4 +100,8 @@ const (
 
 	NotAvailableLabel = "Not available"
 	BackendCmd        = "avalanche-cli-backend"
+
+	AvalancheGoCompatibilityURL  = "https://raw.githubusercontent.com/ava-labs/avalanchego/master/version/compatibility.json"
```
Comment (felipemadero) [inline pkg/constants/constants.go:104]: also add RPC here?

File: pkg/vm/compatibility.go [hunk 10]
```diff
@@ -0,0 +1,95 @@
...
+	if err != nil {
+		return "", err
+	}
+
+	eligibleVersions, ok := parsedCompat[strconv.Itoa(rpcVersion)]
```
Comment (holisticode) [inline pkg/vm/compatibility.go:64]: Are these not semver versions? If they are, semver has inbuilt sorting if I remember correctly. Otherwise the sorting can actually get tricky.

File: pkg/vm/compatibility_test.go [hunk 11]
```diff
@@ -0,0 +1,161 @@
...
+
+const (
+	testAvagoVersion         = "v0.4.2"
+	testUnlistedAvagoVersion = "v0.4.3"
+)
+
+var (
+	testSubnetEVMCompat = []byte("{\"rpcChainVMProtocolVersion\": {\"v0.4.2\": 18,\"v0.4.1\": 18,\"v0.4.0\": 17}}")
+	testAvagoCompat     = []byte("{\"19\": [\"v1.9.2\"],\"18\": [\"v1.9.1\"],\"17\": [\"v1.9.0\",\"v1.8.0\"]}")
+	testAvagoCompat2    = []byte("{\"19\": [\"v1.9.2\", \"v1.9.1\"],\"18\": [\"v1.9.0\"]}")
```
Comment (holisticode) [inline pkg/vm/compatibility_test.go:24]: It might be interesting to have tests with more "tricky" versions, e.g. v1.9.11 vs v.1.9.1 vs 1.9.01 etc.

File: pkg/vm/compatibility_test.go [hunk 12]
```diff
@@ -0,0 +1,161 @@
...
+		latestVersion   string
+		expectedVersion string
+		expectedErr     error
+	}
+
+	tests := []versionTest{
+		{
+			rpc:             19,
+			testData:        testAvagoCompat,
+			latestVersion:   "v1.9.2",
```
Comment (holisticode) [inline pkg/vm/compatibility_test.go:96]: Not sure we want to limit the tests to just these hardcoded versions?

File: tests/e2e/commands/subnet.go [hunk 13]
```diff
@@ -151,7 +151,13 @@ func DeleteSubnetConfig(subnetName string) {
 // Returns the deploy output
 /* #nosec G204 */
 func DeploySubnetLocally(subnetName string) string {
-	return DeploySubnetLocallyWithArgs(subnetName, utils.AvagoVersion, "")
+	return DeploySubnetLocallyWithArgs(subnetName, "", "")
+}
+
+// Returns the deploy output
```
Comment (felipemadero) [inline tests/e2e/commands/subnet.go:157]: obsolete comment

File: tests/e2e/commands/subnet.go [hunk 14]
```diff
@@ -199,6 +205,27 @@ func DeploySubnetLocallyWithArgs(subnetName string, version string, confPath str
 	return string(output)
 }
 
+// Returns the deploy output
```
Comment (felipemadero) [inline tests/e2e/commands/subnet.go:208]: same

File: tests/e2e/testcases/subnet/local/suite.go [hunk 15]
```diff
@@ -164,3 +167,81 @@ var _ = ginkgo.Describe("[Local Subnet]", func() {
 		commands.DeleteSubnetConfig(secondSubnetName)
 	})
 })
+
+var _ = ginkgo.Describe("[Subnet Compatibility]", func() {
+	ginkgo.AfterEach(func() {
+		commands.CleanNetwork()
+		err := utils.DeleteConfigs(subnetName)
```
Comment (holisticode) [inline tests/e2e/testcases/subnet/local/suite.go:174]: pattern if err.... (not repeating)

File: tests/e2e/testcases/packageman/suite.go [hunk 16]
```diff
@@ -20,10 +20,14 @@ const (
 	// is compatible with avago v1.8.x.
 	// This also means we should consider this for the future: How to handle hardforks which make
 	// this test break.:w
-	subnetEVMVersion1 = "v0.3.0"
-	subnetEVMVersion2 = "v0.3.0"
-	avagoVersion1     = "v1.8.0"
-	avagoVersion2     = "v1.8.1"
+	subnetEVMVersion1 = "v0.4.2"
```
Comment (felipemadero) [inline tests/e2e/testcases/packageman/suite.go:23]: prefix with soloAvago?

File: tests/e2e/testcases/subnet/local/suite.go [hunk 17]
```diff
@@ -164,3 +167,81 @@ var _ = ginkgo.Describe("[Local Subnet]", func() {
...
+		gomega.Expect(err).Should(gomega.BeNil())
+		err = utils.DeleteConfigs(secondSubnetName)
+		if err != nil {
+			fmt.Println("Delete config error:", err)
+		}
+		gomega.Expect(err).Should(gomega.BeNil())
+	})
+
+	ginkgo.It("can deploy a subnet-evm with old version", func() {
+		subnetEVMVersion := "v0.4.2"
```
Comment (holisticode) [inline tests/e2e/testcases/subnet/local/suite.go:187]: Couldn't these be quickly get outdated if they are hardcoded?

File: tests/e2e/utils/helpers.go [hunk 18]
```diff
@@ -257,6 +257,12 @@ func DeleteBins() error {
 	return nil
 }
 
+func DeleteCustomBinary(vmName string) {
+	vmPath := path.Join(GetBaseDir(), constants.VMDir, vmName)
+	// ignore error, file may not exist
+	os.RemoveAll(vmPath)
```
Comment (holisticode) [inline tests/e2e/utils/helpers.go:263]: Doesn't this result in a linter errror?

**Review by felipemadero — COMMENTED** [review]
LGTM. Nits

File: pkg/vm/compatibility.go (hunk 10 above)
Comment (dasconnor) [reply pkg/vm/compatibility.go:64]: These are not actually semvers, they are just ints. Ex: https://github.com/ava-labs/subnet-evm/blob/master/compatibility.json

File: cmd/subnetcmd/deploy.go (hunk 5 above)
[the remark this answers is not in the document]
Comment (dasconnor) [reply cmd/subnetcmd/deploy.go]: I removed the side effect

File: cmd/subnetcmd/deploy.go [hunk 19]
```diff
@@ -678,3 +692,45 @@ func PrintDeployResults(chain string, subnetID ids.ID, blockchainID ids.ID, isFu
 	table.Render()
 	return nil
 }
+
+// Has side effects and will set the version of avalanchego in the package-level avagoVersion variable.
+func checkForInvalidDeployAndSetAvagoVersion(network nw.StatusChecker, configuredRPCVersion int) error {
```
[the remark this answers is not in the document]
Comment (dasconnor) [reply cmd/subnetcmd/deploy.go]: renamed

File: cmd/subnetcmd/deploy_test.go [hunk 20]
```diff
@@ -3,12 +3,25 @@
...
+	"github.com/ava-labs/avalanche-cli/pkg/application"
+	"github.com/ava-labs/avalanchego/utils/logging"
 	"github.com/stretchr/testify/assert"
+	"github.com/stretchr/testify/mock"
 )
 
+const (
+	testAvagoVersion1      = "v1.9.2"
+	testAvagoVersion2      = "v1.9.1"
+	testLatestAvagoVersion = "latest"
```
[the remark this answers is not in the document]
Comment (dasconnor) [reply cmd/subnetcmd/deploy_test.go:20]: Not sure what you're suggesting. We don't just test latest, but latest is a key value to test, so we alias it with a constant here.

File: pkg/application/downloader.go [hunk 21]
```diff
@@ -0,0 +1,78 @@
...
+	"encoding/json"
+	"fmt"
+	"io"
+	"net/http"
+	"os"
+
+	"github.com/ava-labs/avalanche-cli/pkg/constants"
+)
+
+type Downloader interface {
```
[the remark this answers is not in the document]
Comment (dasconnor) [reply pkg/application/downloader.go:22]: Done. As I think you figured out below, I moved a bunch of our http/downloading functionality into this package so we could mock it cleanly for testing.

File: pkg/network/network.go (hunk 4 above)
Comment (dasconnor) [reply pkg/network/network.go]: I don't think there is a semver data type, so I don't think there's anything to do here.

File: pkg/vm/compatibility_test.go (hunk 11 above)
Comment (dasconnor) [reply pkg/vm/compatibility_test.go:24]: This might be interesting for fuzzing purposes, but I don't think it's really necessary. We're really just testing key value matches. The one part that is interesting is that we're testing some semantic version sorting, which could backfire if some strings aren't semvars, but avalanchego does have protections to make sure that's not the case. So I don't think we really need to do anything else here.

File: pkg/vm/compatibility_test.go (hunk 12 above)
Comment (dasconnor) [reply pkg/vm/compatibility_test.go:96]: This isn't actually downloading compatibility files or running any vms, we're just testing that we're parsing the compatibility formats correctly. Fixed versions are the only way to test this.

File: tests/e2e/testcases/subnet/local/suite.go (hunk 17 above)
Comment (dasconnor) [reply tests/e2e/testcases/subnet/local/suite.go:235]: for this particular test, that's actually the point

File: tests/e2e/utils/helpers.go (hunk 18 above)
Comment (dasconnor) [reply tests/e2e/utils/helpers.go:255]: nope! only if you assign the error to a variable I believe

File: cmd/subnetcmd/deploy.go (hunk 5 above)
Comment (dasconnor) [reply cmd/subnetcmd/deploy.go]: removed side effect

File: cmd/subnetcmd/deploy.go (hunk 6 above)
Comment (dasconnor) [reply cmd/subnetcmd/deploy.go]: renamed

File: pkg/constants/constants.go (hunk 9 above)
Comment (dasconnor) [reply pkg/constants/constants.go]: not sure what you mean?

File: pkg/vm/compatibility_test.go (hunk 11 above)
Comment (holisticode) [reply pkg/vm/compatibility_test.go:24]: Are we sure that v1.9.11 is after v1.9.1 in this PR? v1.10.1 after v1.9.1 ? If the comparison is by string, not necessarily.

File: tests/e2e/utils/helpers.go (hunk 18 above)
Comment (holisticode) [reply tests/e2e/utils/helpers.go:255]: Oh interesting. Maybe just with my local linter settings.

File: pkg/network/network.go (hunk 4 above)
Comment (holisticode) [reply pkg/network/network.go]: You're right, there isn't actually such a type

**Review by holisticode — APPROVED** [review]

File: pkg/constants/constants.go (hunk 9 above)
Comment (felipemadero) [reply pkg/constants/constants.go]: both SubnetEVMRPCCompatibilityURL and SpacesVMRPCCompatibilityURL are explicit regarding compatibility refers to RPC version compatibility, but AvalancheGoCompatibilityURL not

**Review by felipemadero — APPROVED** [review]

File: pkg/vm/compatibility_test.go (hunk 11 above)
Comment (dasconnor) [reply pkg/vm/compatibility_test.go:24]: this was indeed a bug, I added a test and switched the sorting to use `semver` instead of string sorting
